#!/usr/bin/env bash

env_file="$HOME/.config/controller-autostart-steam.env"

. $env_file

powerprofilesctl set "$perf_inside"

steam

powerprofilesctl set "$perf_outside"

rm "$lockfile" || echo "cannot delete $lockfile"
